table 80514 "Aircaft Maintenance"
{
    Caption = 'Aircraft Maintenance';
    DataClassification = CustomerContent;

    fields
    {
        field(1; "Entry No."; Integer)
        {
            Caption = 'Entry No.';
            //on each entry for the number it will be auto incremented to know the maintenance number
            AutoIncrement = true;
            //here the data is generated by the system so it can be AutoIncremented
            DataClassification = SystemMetadata;
            MinValue = 0;
        }
        field(2; "Aircraft Registration No."; Code[20])
        {
            Caption = 'Aircraft Registration No.';
            TableRelation = "Aircraft"."Registration No.";
            DataClassification = CustomerContent;
        }
        field(3; "Maintance Type"; Code[20])
        {
            Caption = 'Maintenance Type';
            TableRelation = Maintenance.Code;
            DataClassification = CustomerContent;
        }
        field(4; "Start Date"; Date)
        {
            Caption = 'Start Date';
            DataClassification = CustomerContent;

            trigger OnValidate()
            begin
                // the +1 is to handle the difference so if a start = end it displays 1D and not 0D 
                "Duration" := ("End Date" - "Start Date") + 1;
            end;

        }
        field(5; "End Date"; Date)
        {
            Caption = 'End Date';
            DataClassification = CustomerContent;
            trigger OnValidate()
            begin
                // the +1 is to handle the difference so if a start = end it displays 1D and not 0D 
                "Duration" := ("End Date" - "Start Date") + 1;
            end;

        }
        field(6; "Duration"; Integer)
        {
            Caption = 'Duration';
            Editable = false;
            DataClassification = CustomerContent;
        }
        field(7; "Description"; Text[250])
        {
            Caption = 'Description';
            DataClassification = CustomerContent;
        }
        field(8; "Part Cost"; Decimal)
        {
            Caption = 'Part Cost';
            DecimalPlaces = 0;
            MinValue = 0;
            DataClassification = CustomerContent;

            trigger OnValidate()
            begin
                "Total Cost" := "Part Cost" + "Labor Cost";
            end;
        }

        field(9; "Labor Cost"; Decimal)
        {
            Caption = 'Labor Cost';
            DecimalPlaces = 0;
            MinValue = 0;
            DataClassification = CustomerContent;

            trigger OnValidate()
            begin
                "Total Cost" := "Part Cost" + "Labor Cost";
            end;
        }

        field(10; "Total Cost"; Decimal)
        {
            Caption = 'Total Cost';
            DecimalPlaces = 0;
            MinValue = 0;
            Editable = false; // computed automatically based on user input
            DataClassification = CustomerContent;
        }

    }
    keys
    {
        key(PK; "Entry No.") { Clustered = true; }
        key(Airline; "Aircraft Registration No.") { }
    }
    fieldgroups
    {
        fieldgroup(DropDown; "Aircraft Registration No.", "Entry No.", "Maintance Type") { }
    }
}